config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :blogs
  end
  
  resources :magazines do
    resources :adds
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/add.rb
class Add < ApplicationRecord
  belongs_to :magazine
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/blog.rb
class Admin::Blog < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/magazine.rb
class Magazine < ApplicationRecord
    has_many :adds
end

app/controllers/adds_controller.rb
class AddsController < ApplicationController
  before_action :set_add, only: [:show, :edit, :update, :destroy]
  before_action :set_magazine

  # GET /adds
  # GET /adds.json
  def index
    @adds = @magazine.adds
  end

  # GET /adds/1
  # GET /adds/1.json
  def show
  end

  # GET /adds/new
  def new
    @add = @magazine.adds.new
  end

  # GET /adds/1/edit
  def edit
  end

  # POST /adds
  # POST /adds.json
  def create
    @add = @magazine.adds.new(add_params)

    respond_to do |format|
      if @add.save
        format.html { redirect_to [@magazine, @add], notice: 'Add was successfully created.' }
        format.json { render :show, status: :created, location: @add }
      else
        format.html { render :new }
        format.json { render json: @add.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adds/1
  # PATCH/PUT /adds/1.json
  def update
    respond_to do |format|
      if @add.update(add_params)
        format.html { redirect_to  [@magazine, @add], notice: 'Add was successfully updated.' }
        format.json { render :show, status: :ok, location: @add }
      else
        format.html { render :edit }
        format.json { render json: @add.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adds/1
  # DELETE /adds/1.json
  def destroy
    @add.destroy
    respond_to do |format|
      format.html { redirect_to magazine_adds_url, notice: 'Add was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_add
      @add = Add.find(params[:id])
    end

    def set_magazine
      @magazine = Magazine.find(params[:magazine_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def add_params
      params.require(:add).permit(:content, :brand, :magazine_id)
    end
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController
  before_action :set_admin_blog, only: [:show, :edit, :update, :destroy]

  # GET /admin/blogs
  # GET /admin/blogs.json
  def index
    @admin_blogs = Admin::Blog.all
  end

  # GET /admin/blogs/1
  # GET /admin/blogs/1.json
  def show
  end

  # GET /admin/blogs/new
  def new
    @admin_blog = Admin::Blog.new
  end

  # GET /admin/blogs/1/edit
  def edit
  end

  # POST /admin/blogs
  # POST /admin/blogs.json
  def create
    @admin_blog = Admin::Blog.new(admin_blog_params)

    respond_to do |format|
      if @admin_blog.save
        format.html { redirect_to @admin_blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @admin_blog }
      else
        format.html { render :new }
        format.json { render json: @admin_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/blogs/1
  # PATCH/PUT /admin/blogs/1.json
  def update
    respond_to do |format|
      if @admin_blog.update(admin_blog_params)
        format.html { redirect_to @admin_blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_blog }
      else
        format.html { render :edit }
        format.json { render json: @admin_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/blogs/1
  # DELETE /admin/blogs/1.json
  def destroy
    @admin_blog.destroy
    respond_to do |format|
      format.html { redirect_to admin_blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_blog
      @admin_blog = Admin::Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_blog_params
      params.require(:admin_blog).permit(:title, :content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  before_action :set_magazine, only: [:show, :edit, :update, :destroy]

  # GET /magazines
  # GET /magazines.json
  def index
    @magazines = Magazine.all
  end

  # GET /magazines/1
  # GET /magazines/1.json
  def show
  end

  # GET /magazines/new
  def new
    @magazine = Magazine.new
  end

  # GET /magazines/1/edit
  def edit
  end

  # POST /magazines
  # POST /magazines.json
  def create
    @magazine = Magazine.new(magazine_params)

    respond_to do |format|
      if @magazine.save
        format.html { redirect_to @magazine, notice: 'Magazine was successfully created.' }
        format.json { render :show, status: :created, location: @magazine }
      else
        format.html { render :new }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazines/1
  # PATCH/PUT /magazines/1.json
  def update
    respond_to do |format|
      if @magazine.update(magazine_params)
        format.html { redirect_to @magazine, notice: 'Magazine was successfully updated.' }
        format.json { render :show, status: :ok, location: @magazine }
      else
        format.html { render :edit }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazines/1
  # DELETE /magazines/1.json
  def destroy
    @magazine.destroy
    respond_to do |format|
      format.html { redirect_to magazines_url, notice: 'Magazine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magazine
      @magazine = Magazine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def magazine_params
      params.require(:magazine).permit(:name)
    end
end

app/helpers/adds_helper.rb
module AddsHelper
end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/views/adds/_form.html.erb
<%= form_with(model: [@magazine, add], local: true) do |form| %>
  <% if add.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(add.errors.count, "error") %> prohibited this add from being saved:</h2>

      <ul>
      <% add.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :magazine_id %>
    <%= form.text_field :magazine_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/adds/edit.html.erb
<h1>Editing Add</h1>

<%= render 'form', add: @add %>

<%= link_to 'Show', [@magazine, @add] %> |
<%= link_to 'Back', magazine_adds_path(@magazine) %>

app/views/adds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Adds</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Brand</th>
      <th>Magazine</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adds.each do |add| %>
      <tr>
        <td><%= add.content %></td>
        <td><%= add.brand %></td>
        <td><%= link_to add.magazine.name, add.magazine %></td>
        <td><%= link_to 'Show', [@magazine, add] %></td>
        <td><%= link_to 'Edit', edit_magazine_add_path(@magazine, add) %></td>
        <td><%= link_to 'Destroy', [@magazine, add], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Add', new_magazine_add_path(@magazine)  %>

app/views/adds/new.html.erb
<h1>New Add</h1>

<%= render 'form', add: @add %>

<%= link_to 'Back', magazine_adds_path(@magazine) %>

app/views/adds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @add.content %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @add.brand %>
</p>

<p>
  <strong>Magazine:</strong>
  <%= @add.magazine.name %>
</p>

<%= link_to 'Edit', edit_magazine_add_path(@magazine, @add) %> |
<%= link_to 'Back', magazine_adds_path(@magazine) %>

app/views/admin/blogs/_form.html.erb
<%= form_with(model: admin_blog, local: true) do |form| %>
  <% if admin_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_blog.errors.count, "error") %> prohibited this admin_blog from being saved:</h2>

      <ul>
      <% admin_blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/blogs/edit.html.erb
<h1>Editing Admin Blog</h1>

<%= render 'form', admin_blog: @admin_blog %>

<%= link_to 'Show', @admin_blog %> |
<%= link_to 'Back', admin_blogs_path %>

app/views/admin/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_blogs.each do |admin_blog| %>
      <tr>
        <td><%= admin_blog.title %></td>
        <td><%= admin_blog.content %></td>
        <td><%= link_to 'Show', admin_blog %></td>
        <td><%= link_to 'Edit', edit_admin_blog_path(admin_blog) %></td>
        <td><%= link_to 'Destroy', admin_blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Blog', new_admin_blog_path %>

app/views/admin/blogs/new.html.erb
<h1>New Admin Blog</h1>

<%= render 'form', admin_blog: @admin_blog %>

<%= link_to 'Back', admin_blogs_path %>

app/views/admin/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @admin_blog.content %>
</p>

<%= link_to 'Edit', edit_admin_blog_path(@admin_blog) %> |
<%= link_to 'Back', admin_blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MagZ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/magazines/_form.html.erb
<%= form_with(model: magazine, local: true) do |form| %>
  <% if magazine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(magazine.errors.count, "error") %> prohibited this magazine from being saved:</h2>

      <ul>
      <% magazine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/magazines/edit.html.erb
<h1>Editing Magazine</h1>

<%= render 'form', magazine: @magazine %>

<%= link_to 'Show', @magazine %> |
<%= link_to 'Back', magazines_path %>

app/views/magazines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Magazines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @magazines.each do |magazine| %>
      <tr>
        <td><%= magazine.name %></td>
        <td><%= link_to 'Show', magazine %></td>
        <td><%= link_to 'Edit', edit_magazine_path(magazine) %></td>
        <td><%= link_to 'Destroy', magazine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Magazine', new_magazine_path %>

app/views/magazines/new.html.erb
<h1>New Magazine</h1>

<%= render 'form', magazine: @magazine %>

<%= link_to 'Back', magazines_path %>

app/views/magazines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @magazine.name %>
</p>

<%= link_to 'Edit', edit_magazine_path(@magazine) %> |
<%= link_to 'Back', magazines_path %>